# Generated by Django 5.2.12 on 2026-03-26 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sector_tag', models.CharField(blank=True, max_length=120)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('base_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_tenure_months', models.PositiveIntegerField(default=12)),
                ('minimum_score', models.PositiveIntegerField(default=55)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tenure_months', models.PositiveIntegerField(default=3)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit_score', models.PositiveIntegerField(default=0)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('manual_review', 'Manual Review'), ('declined', 'Declined')], default='manual_review', max_length=16)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected'), ('repaid', 'Repaid')], default='applied', max_length=16)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('score_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loans.loanproduct')),
            ],
        ),
    ]
