# Generated by Django 5.2.12 on 2026-03-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='next_repayment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
